services:
  # --- SOURCE DE DONNÉES NoSQL ---
  sales_mongodb:
    image: mongo:latest
    container_name: sales_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: negui
      MONGO_INITDB_ROOT_PASSWORD: Nekarimo@1
    networks:
      - dataplatform

  # --- STOCKAGE OBJET ---
  minio:
    image: minio/minio:latest
    container_name: sales_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dataplatform

  # --- INITIALISATION DES BUCKETS ---
  minio-client:
    image: minio/mc:latest
    container_name: sales_minio_client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      mc mb myminio/bronze --ignore-existing;
      mc mb myminio/silver --ignore-existing;
      mc mb myminio/gold --ignore-existing;
      exit 0;
      "
    networks:
      - dataplatform

  # --- PLATEFORME DATA ---
  marimo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_marimo
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_healthy
      sales_mongodb:
        condition: service_started
    volumes:
      - ./notebooks:/app
      - ./data:/app/data
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MONGO_URI=mongodb://negui:Nekarimo%401@sales_mongodb:27017/gescom?authSource=admin
      # LA VARIABLE MAGIQUE EST ICI (formatée correctement en liste)
      - PYSPARK_SUBMIT_ARGS=--conf "spark.driver.extraJavaOptions=--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED" --conf "spark.executor.extraJavaOptions=--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED" pyspark-shell
    command: marimo edit --host 0.0.0.0 --port 8080 /app --no-token
    networks:
      - dataplatform

volumes:
  minio_data:

networks:
  dataplatform:
    driver: bridge