services:
  postgres:
    image: postgres:16-alpine
    container_name: sales_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testspark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ndiouf@1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testspark"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dataplatform

  minio:
    image: minio/minio:latest
    container_name: sales_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      PYSPARK_SUBMIT_ARGS: >
        --packages org.postgresql:postgresql:42.7.3,org.apache.hadoop:hadoop-aws:3.3.4
        pyspark-shell
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dataplatform

  minio-client:
    image: minio/mc:latest
    container_name: sales_minio_client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      mc mb myminio/bronze --ignore-existing;
      mc mb myminio/silver --ignore-existing;
      mc mb myminio/gold --ignore-existing;
      echo 'âœ… Buckets created';
      exit 0;
      "
    networks:
      - dataplatform

  marimo-spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_marimo_spark
    ports:
      - "8080:8080"   # Marimo UI
      - "4040:4040"   # Spark UI
    depends_on:
      postgres:
        condition: service_healthy
      minio-client:
        condition: service_completed_successfully
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      SPARK_MASTER: local[*]
    networks:
      - dataplatform

volumes:
  minio_data:
  postgres_data:

networks:
  dataplatform:
    driver: bridge